### ISSUE TITLE
Consider adding Rust Juniper Playground to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [Yama-Tomo/rust-juniper-playground#2]
Hey @Yama-Tomo, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by Yama-Tomo** [comment]
@billy1624 Thanks for the comment!!
This repository is a sample repository for learning RUST. (I'm new to RUST, so the code is probably not refined... :sweat_smile: )

Is it appropriate to add this to your list :eyes: ?

**Comment by billy1624** [comment]
Hey @Yama-Tomo, you can add your project under https://github.com/SeaQL/sea-orm/blob/master/COMMUNITY.md#open-source-projects if you feel comfortable doing it :D
